// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package fileformat

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-snowflake.fileFormat.FileFormat",
		reflect.TypeOf((*FileFormat)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "allowDuplicate", GoGetter: "AllowDuplicate"},
			_jsii_.MemberProperty{JsiiProperty: "allowDuplicateInput", GoGetter: "AllowDuplicateInput"},
			_jsii_.MemberProperty{JsiiProperty: "binaryAsText", GoGetter: "BinaryAsText"},
			_jsii_.MemberProperty{JsiiProperty: "binaryAsTextInput", GoGetter: "BinaryAsTextInput"},
			_jsii_.MemberProperty{JsiiProperty: "binaryFormat", GoGetter: "BinaryFormat"},
			_jsii_.MemberProperty{JsiiProperty: "binaryFormatInput", GoGetter: "BinaryFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "comment", GoGetter: "Comment"},
			_jsii_.MemberProperty{JsiiProperty: "commentInput", GoGetter: "CommentInput"},
			_jsii_.MemberProperty{JsiiProperty: "compression", GoGetter: "Compression"},
			_jsii_.MemberProperty{JsiiProperty: "compressionInput", GoGetter: "CompressionInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "database", GoGetter: "Database"},
			_jsii_.MemberProperty{JsiiProperty: "databaseInput", GoGetter: "DatabaseInput"},
			_jsii_.MemberProperty{JsiiProperty: "dateFormat", GoGetter: "DateFormat"},
			_jsii_.MemberProperty{JsiiProperty: "dateFormatInput", GoGetter: "DateFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "disableAutoConvert", GoGetter: "DisableAutoConvert"},
			_jsii_.MemberProperty{JsiiProperty: "disableAutoConvertInput", GoGetter: "DisableAutoConvertInput"},
			_jsii_.MemberProperty{JsiiProperty: "disableSnowflakeData", GoGetter: "DisableSnowflakeData"},
			_jsii_.MemberProperty{JsiiProperty: "disableSnowflakeDataInput", GoGetter: "DisableSnowflakeDataInput"},
			_jsii_.MemberProperty{JsiiProperty: "emptyFieldAsNull", GoGetter: "EmptyFieldAsNull"},
			_jsii_.MemberProperty{JsiiProperty: "emptyFieldAsNullInput", GoGetter: "EmptyFieldAsNullInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableOctal", GoGetter: "EnableOctal"},
			_jsii_.MemberProperty{JsiiProperty: "enableOctalInput", GoGetter: "EnableOctalInput"},
			_jsii_.MemberProperty{JsiiProperty: "encoding", GoGetter: "Encoding"},
			_jsii_.MemberProperty{JsiiProperty: "encodingInput", GoGetter: "EncodingInput"},
			_jsii_.MemberProperty{JsiiProperty: "errorOnColumnCountMismatch", GoGetter: "ErrorOnColumnCountMismatch"},
			_jsii_.MemberProperty{JsiiProperty: "errorOnColumnCountMismatchInput", GoGetter: "ErrorOnColumnCountMismatchInput"},
			_jsii_.MemberProperty{JsiiProperty: "escape", GoGetter: "Escape"},
			_jsii_.MemberProperty{JsiiProperty: "escapeInput", GoGetter: "EscapeInput"},
			_jsii_.MemberProperty{JsiiProperty: "escapeUnenclosedField", GoGetter: "EscapeUnenclosedField"},
			_jsii_.MemberProperty{JsiiProperty: "escapeUnenclosedFieldInput", GoGetter: "EscapeUnenclosedFieldInput"},
			_jsii_.MemberProperty{JsiiProperty: "fieldDelimiter", GoGetter: "FieldDelimiter"},
			_jsii_.MemberProperty{JsiiProperty: "fieldDelimiterInput", GoGetter: "FieldDelimiterInput"},
			_jsii_.MemberProperty{JsiiProperty: "fieldOptionallyEnclosedBy", GoGetter: "FieldOptionallyEnclosedBy"},
			_jsii_.MemberProperty{JsiiProperty: "fieldOptionallyEnclosedByInput", GoGetter: "FieldOptionallyEnclosedByInput"},
			_jsii_.MemberProperty{JsiiProperty: "fileExtension", GoGetter: "FileExtension"},
			_jsii_.MemberProperty{JsiiProperty: "fileExtensionInput", GoGetter: "FileExtensionInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "formatType", GoGetter: "FormatType"},
			_jsii_.MemberProperty{JsiiProperty: "formatTypeInput", GoGetter: "FormatTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberProperty{JsiiProperty: "fullyQualifiedName", GoGetter: "FullyQualifiedName"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreUtf8Errors", GoGetter: "IgnoreUtf8Errors"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreUtf8ErrorsInput", GoGetter: "IgnoreUtf8ErrorsInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "nullIf", GoGetter: "NullIf"},
			_jsii_.MemberProperty{JsiiProperty: "nullIfInput", GoGetter: "NullIfInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "parseHeader", GoGetter: "ParseHeader"},
			_jsii_.MemberProperty{JsiiProperty: "parseHeaderInput", GoGetter: "ParseHeaderInput"},
			_jsii_.MemberProperty{JsiiProperty: "preserveSpace", GoGetter: "PreserveSpace"},
			_jsii_.MemberProperty{JsiiProperty: "preserveSpaceInput", GoGetter: "PreserveSpaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putTimeouts", GoMethod: "PutTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "recordDelimiter", GoGetter: "RecordDelimiter"},
			_jsii_.MemberProperty{JsiiProperty: "recordDelimiterInput", GoGetter: "RecordDelimiterInput"},
			_jsii_.MemberProperty{JsiiProperty: "replaceInvalidCharacters", GoGetter: "ReplaceInvalidCharacters"},
			_jsii_.MemberProperty{JsiiProperty: "replaceInvalidCharactersInput", GoGetter: "ReplaceInvalidCharactersInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowDuplicate", GoMethod: "ResetAllowDuplicate"},
			_jsii_.MemberMethod{JsiiMethod: "resetBinaryAsText", GoMethod: "ResetBinaryAsText"},
			_jsii_.MemberMethod{JsiiMethod: "resetBinaryFormat", GoMethod: "ResetBinaryFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetComment", GoMethod: "ResetComment"},
			_jsii_.MemberMethod{JsiiMethod: "resetCompression", GoMethod: "ResetCompression"},
			_jsii_.MemberMethod{JsiiMethod: "resetDateFormat", GoMethod: "ResetDateFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableAutoConvert", GoMethod: "ResetDisableAutoConvert"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableSnowflakeData", GoMethod: "ResetDisableSnowflakeData"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmptyFieldAsNull", GoMethod: "ResetEmptyFieldAsNull"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableOctal", GoMethod: "ResetEnableOctal"},
			_jsii_.MemberMethod{JsiiMethod: "resetEncoding", GoMethod: "ResetEncoding"},
			_jsii_.MemberMethod{JsiiMethod: "resetErrorOnColumnCountMismatch", GoMethod: "ResetErrorOnColumnCountMismatch"},
			_jsii_.MemberMethod{JsiiMethod: "resetEscape", GoMethod: "ResetEscape"},
			_jsii_.MemberMethod{JsiiMethod: "resetEscapeUnenclosedField", GoMethod: "ResetEscapeUnenclosedField"},
			_jsii_.MemberMethod{JsiiMethod: "resetFieldDelimiter", GoMethod: "ResetFieldDelimiter"},
			_jsii_.MemberMethod{JsiiMethod: "resetFieldOptionallyEnclosedBy", GoMethod: "ResetFieldOptionallyEnclosedBy"},
			_jsii_.MemberMethod{JsiiMethod: "resetFileExtension", GoMethod: "ResetFileExtension"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIgnoreUtf8Errors", GoMethod: "ResetIgnoreUtf8Errors"},
			_jsii_.MemberMethod{JsiiMethod: "resetNullIf", GoMethod: "ResetNullIf"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetParseHeader", GoMethod: "ResetParseHeader"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreserveSpace", GoMethod: "ResetPreserveSpace"},
			_jsii_.MemberMethod{JsiiMethod: "resetRecordDelimiter", GoMethod: "ResetRecordDelimiter"},
			_jsii_.MemberMethod{JsiiMethod: "resetReplaceInvalidCharacters", GoMethod: "ResetReplaceInvalidCharacters"},
			_jsii_.MemberMethod{JsiiMethod: "resetSkipBlankLines", GoMethod: "ResetSkipBlankLines"},
			_jsii_.MemberMethod{JsiiMethod: "resetSkipByteOrderMark", GoMethod: "ResetSkipByteOrderMark"},
			_jsii_.MemberMethod{JsiiMethod: "resetSkipHeader", GoMethod: "ResetSkipHeader"},
			_jsii_.MemberMethod{JsiiMethod: "resetStripNullValues", GoMethod: "ResetStripNullValues"},
			_jsii_.MemberMethod{JsiiMethod: "resetStripOuterArray", GoMethod: "ResetStripOuterArray"},
			_jsii_.MemberMethod{JsiiMethod: "resetStripOuterElement", GoMethod: "ResetStripOuterElement"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeFormat", GoMethod: "ResetTimeFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeouts", GoMethod: "ResetTimeouts"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimestampFormat", GoMethod: "ResetTimestampFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrimSpace", GoMethod: "ResetTrimSpace"},
			_jsii_.MemberProperty{JsiiProperty: "schema", GoGetter: "Schema"},
			_jsii_.MemberProperty{JsiiProperty: "schemaInput", GoGetter: "SchemaInput"},
			_jsii_.MemberProperty{JsiiProperty: "skipBlankLines", GoGetter: "SkipBlankLines"},
			_jsii_.MemberProperty{JsiiProperty: "skipBlankLinesInput", GoGetter: "SkipBlankLinesInput"},
			_jsii_.MemberProperty{JsiiProperty: "skipByteOrderMark", GoGetter: "SkipByteOrderMark"},
			_jsii_.MemberProperty{JsiiProperty: "skipByteOrderMarkInput", GoGetter: "SkipByteOrderMarkInput"},
			_jsii_.MemberProperty{JsiiProperty: "skipHeader", GoGetter: "SkipHeader"},
			_jsii_.MemberProperty{JsiiProperty: "skipHeaderInput", GoGetter: "SkipHeaderInput"},
			_jsii_.MemberProperty{JsiiProperty: "stripNullValues", GoGetter: "StripNullValues"},
			_jsii_.MemberProperty{JsiiProperty: "stripNullValuesInput", GoGetter: "StripNullValuesInput"},
			_jsii_.MemberProperty{JsiiProperty: "stripOuterArray", GoGetter: "StripOuterArray"},
			_jsii_.MemberProperty{JsiiProperty: "stripOuterArrayInput", GoGetter: "StripOuterArrayInput"},
			_jsii_.MemberProperty{JsiiProperty: "stripOuterElement", GoGetter: "StripOuterElement"},
			_jsii_.MemberProperty{JsiiProperty: "stripOuterElementInput", GoGetter: "StripOuterElementInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timeFormat", GoGetter: "TimeFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timeFormatInput", GoGetter: "TimeFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "timeouts", GoGetter: "Timeouts"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutsInput", GoGetter: "TimeoutsInput"},
			_jsii_.MemberProperty{JsiiProperty: "timestampFormat", GoGetter: "TimestampFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timestampFormatInput", GoGetter: "TimestampFormatInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "trimSpace", GoGetter: "TrimSpace"},
			_jsii_.MemberProperty{JsiiProperty: "trimSpaceInput", GoGetter: "TrimSpaceInput"},
		},
		func() interface{} {
			j := jsiiProxy_FileFormat{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-snowflake.fileFormat.FileFormatConfig",
		reflect.TypeOf((*FileFormatConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-snowflake.fileFormat.FileFormatTimeouts",
		reflect.TypeOf((*FileFormatTimeouts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-snowflake.fileFormat.FileFormatTimeoutsOutputReference",
		reflect.TypeOf((*FileFormatTimeoutsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "create", GoGetter: "Create"},
			_jsii_.MemberProperty{JsiiProperty: "createInput", GoGetter: "CreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "delete", GoGetter: "Delete"},
			_jsii_.MemberProperty{JsiiProperty: "deleteInput", GoGetter: "DeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "read", GoGetter: "Read"},
			_jsii_.MemberProperty{JsiiProperty: "readInput", GoGetter: "ReadInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreate", GoMethod: "ResetCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelete", GoMethod: "ResetDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resetRead", GoMethod: "ResetRead"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpdate", GoMethod: "ResetUpdate"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "update", GoGetter: "Update"},
			_jsii_.MemberProperty{JsiiProperty: "updateInput", GoGetter: "UpdateInput"},
		},
		func() interface{} {
			j := jsiiProxy_FileFormatTimeoutsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexObject)
			return &j
		},
	)
}
