// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-snowflake.provider.SnowflakeProvider",
		reflect.TypeOf((*SnowflakeProvider)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accountName", GoGetter: "AccountName"},
			_jsii_.MemberProperty{JsiiProperty: "accountNameInput", GoGetter: "AccountNameInput"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "alias", GoGetter: "Alias"},
			_jsii_.MemberProperty{JsiiProperty: "aliasInput", GoGetter: "AliasInput"},
			_jsii_.MemberProperty{JsiiProperty: "authenticator", GoGetter: "Authenticator"},
			_jsii_.MemberProperty{JsiiProperty: "authenticatorInput", GoGetter: "AuthenticatorInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clientIp", GoGetter: "ClientIp"},
			_jsii_.MemberProperty{JsiiProperty: "clientIpInput", GoGetter: "ClientIpInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientRequestMfaToken", GoGetter: "ClientRequestMfaToken"},
			_jsii_.MemberProperty{JsiiProperty: "clientRequestMfaTokenInput", GoGetter: "ClientRequestMfaTokenInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientStoreTemporaryCredential", GoGetter: "ClientStoreTemporaryCredential"},
			_jsii_.MemberProperty{JsiiProperty: "clientStoreTemporaryCredentialInput", GoGetter: "ClientStoreTemporaryCredentialInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientTimeout", GoGetter: "ClientTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "clientTimeoutInput", GoGetter: "ClientTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "disableConsoleLogin", GoGetter: "DisableConsoleLogin"},
			_jsii_.MemberProperty{JsiiProperty: "disableConsoleLoginInput", GoGetter: "DisableConsoleLoginInput"},
			_jsii_.MemberProperty{JsiiProperty: "disableQueryContextCache", GoGetter: "DisableQueryContextCache"},
			_jsii_.MemberProperty{JsiiProperty: "disableQueryContextCacheInput", GoGetter: "DisableQueryContextCacheInput"},
			_jsii_.MemberProperty{JsiiProperty: "disableTelemetry", GoGetter: "DisableTelemetry"},
			_jsii_.MemberProperty{JsiiProperty: "disableTelemetryInput", GoGetter: "DisableTelemetryInput"},
			_jsii_.MemberProperty{JsiiProperty: "driverTracing", GoGetter: "DriverTracing"},
			_jsii_.MemberProperty{JsiiProperty: "driverTracingInput", GoGetter: "DriverTracingInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableSingleUseRefreshTokens", GoGetter: "EnableSingleUseRefreshTokens"},
			_jsii_.MemberProperty{JsiiProperty: "enableSingleUseRefreshTokensInput", GoGetter: "EnableSingleUseRefreshTokensInput"},
			_jsii_.MemberProperty{JsiiProperty: "experimentalFeaturesEnabled", GoGetter: "ExperimentalFeaturesEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "experimentalFeaturesEnabledInput", GoGetter: "ExperimentalFeaturesEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "externalBrowserTimeout", GoGetter: "ExternalBrowserTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "externalBrowserTimeoutInput", GoGetter: "ExternalBrowserTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberProperty{JsiiProperty: "host", GoGetter: "Host"},
			_jsii_.MemberProperty{JsiiProperty: "hostInput", GoGetter: "HostInput"},
			_jsii_.MemberProperty{JsiiProperty: "includeRetryReason", GoGetter: "IncludeRetryReason"},
			_jsii_.MemberProperty{JsiiProperty: "includeRetryReasonInput", GoGetter: "IncludeRetryReasonInput"},
			_jsii_.MemberProperty{JsiiProperty: "insecureMode", GoGetter: "InsecureMode"},
			_jsii_.MemberProperty{JsiiProperty: "insecureModeInput", GoGetter: "InsecureModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "jwtClientTimeout", GoGetter: "JwtClientTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "jwtClientTimeoutInput", GoGetter: "JwtClientTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "jwtExpireTimeout", GoGetter: "JwtExpireTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "jwtExpireTimeoutInput", GoGetter: "JwtExpireTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "keepSessionAlive", GoGetter: "KeepSessionAlive"},
			_jsii_.MemberProperty{JsiiProperty: "keepSessionAliveInput", GoGetter: "KeepSessionAliveInput"},
			_jsii_.MemberProperty{JsiiProperty: "loginTimeout", GoGetter: "LoginTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "loginTimeoutInput", GoGetter: "LoginTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "logQueryParameters", GoGetter: "LogQueryParameters"},
			_jsii_.MemberProperty{JsiiProperty: "logQueryParametersInput", GoGetter: "LogQueryParametersInput"},
			_jsii_.MemberProperty{JsiiProperty: "logQueryText", GoGetter: "LogQueryText"},
			_jsii_.MemberProperty{JsiiProperty: "logQueryTextInput", GoGetter: "LogQueryTextInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxRetryCount", GoGetter: "MaxRetryCount"},
			_jsii_.MemberProperty{JsiiProperty: "maxRetryCountInput", GoGetter: "MaxRetryCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "metaAttributes", GoGetter: "MetaAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "oauthAuthorizationUrl", GoGetter: "OauthAuthorizationUrl"},
			_jsii_.MemberProperty{JsiiProperty: "oauthAuthorizationUrlInput", GoGetter: "OauthAuthorizationUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "oauthClientId", GoGetter: "OauthClientId"},
			_jsii_.MemberProperty{JsiiProperty: "oauthClientIdInput", GoGetter: "OauthClientIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "oauthClientSecret", GoGetter: "OauthClientSecret"},
			_jsii_.MemberProperty{JsiiProperty: "oauthClientSecretInput", GoGetter: "OauthClientSecretInput"},
			_jsii_.MemberProperty{JsiiProperty: "oauthRedirectUri", GoGetter: "OauthRedirectUri"},
			_jsii_.MemberProperty{JsiiProperty: "oauthRedirectUriInput", GoGetter: "OauthRedirectUriInput"},
			_jsii_.MemberProperty{JsiiProperty: "oauthScope", GoGetter: "OauthScope"},
			_jsii_.MemberProperty{JsiiProperty: "oauthScopeInput", GoGetter: "OauthScopeInput"},
			_jsii_.MemberProperty{JsiiProperty: "oauthTokenRequestUrl", GoGetter: "OauthTokenRequestUrl"},
			_jsii_.MemberProperty{JsiiProperty: "oauthTokenRequestUrlInput", GoGetter: "OauthTokenRequestUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "ocspFailOpen", GoGetter: "OcspFailOpen"},
			_jsii_.MemberProperty{JsiiProperty: "ocspFailOpenInput", GoGetter: "OcspFailOpenInput"},
			_jsii_.MemberProperty{JsiiProperty: "oktaUrl", GoGetter: "OktaUrl"},
			_jsii_.MemberProperty{JsiiProperty: "oktaUrlInput", GoGetter: "OktaUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "organizationName", GoGetter: "OrganizationName"},
			_jsii_.MemberProperty{JsiiProperty: "organizationNameInput", GoGetter: "OrganizationNameInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "params", GoGetter: "Params"},
			_jsii_.MemberProperty{JsiiProperty: "paramsInput", GoGetter: "ParamsInput"},
			_jsii_.MemberProperty{JsiiProperty: "passcode", GoGetter: "Passcode"},
			_jsii_.MemberProperty{JsiiProperty: "passcodeInPassword", GoGetter: "PasscodeInPassword"},
			_jsii_.MemberProperty{JsiiProperty: "passcodeInPasswordInput", GoGetter: "PasscodeInPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "passcodeInput", GoGetter: "PasscodeInput"},
			_jsii_.MemberProperty{JsiiProperty: "password", GoGetter: "Password"},
			_jsii_.MemberProperty{JsiiProperty: "passwordInput", GoGetter: "PasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "port", GoGetter: "Port"},
			_jsii_.MemberProperty{JsiiProperty: "portInput", GoGetter: "PortInput"},
			_jsii_.MemberProperty{JsiiProperty: "previewFeaturesEnabled", GoGetter: "PreviewFeaturesEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "previewFeaturesEnabledInput", GoGetter: "PreviewFeaturesEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "privateKey", GoGetter: "PrivateKey"},
			_jsii_.MemberProperty{JsiiProperty: "privateKeyInput", GoGetter: "PrivateKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "privateKeyPassphrase", GoGetter: "PrivateKeyPassphrase"},
			_jsii_.MemberProperty{JsiiProperty: "privateKeyPassphraseInput", GoGetter: "PrivateKeyPassphraseInput"},
			_jsii_.MemberProperty{JsiiProperty: "profile", GoGetter: "Profile"},
			_jsii_.MemberProperty{JsiiProperty: "profileInput", GoGetter: "ProfileInput"},
			_jsii_.MemberProperty{JsiiProperty: "protocol", GoGetter: "Protocol"},
			_jsii_.MemberProperty{JsiiProperty: "protocolInput", GoGetter: "ProtocolInput"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "requestTimeout", GoGetter: "RequestTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "requestTimeoutInput", GoGetter: "RequestTimeoutInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccountName", GoMethod: "ResetAccountName"},
			_jsii_.MemberMethod{JsiiMethod: "resetAlias", GoMethod: "ResetAlias"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuthenticator", GoMethod: "ResetAuthenticator"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientIp", GoMethod: "ResetClientIp"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientRequestMfaToken", GoMethod: "ResetClientRequestMfaToken"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientStoreTemporaryCredential", GoMethod: "ResetClientStoreTemporaryCredential"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientTimeout", GoMethod: "ResetClientTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableConsoleLogin", GoMethod: "ResetDisableConsoleLogin"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableQueryContextCache", GoMethod: "ResetDisableQueryContextCache"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableTelemetry", GoMethod: "ResetDisableTelemetry"},
			_jsii_.MemberMethod{JsiiMethod: "resetDriverTracing", GoMethod: "ResetDriverTracing"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableSingleUseRefreshTokens", GoMethod: "ResetEnableSingleUseRefreshTokens"},
			_jsii_.MemberMethod{JsiiMethod: "resetExperimentalFeaturesEnabled", GoMethod: "ResetExperimentalFeaturesEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetExternalBrowserTimeout", GoMethod: "ResetExternalBrowserTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetHost", GoMethod: "ResetHost"},
			_jsii_.MemberMethod{JsiiMethod: "resetIncludeRetryReason", GoMethod: "ResetIncludeRetryReason"},
			_jsii_.MemberMethod{JsiiMethod: "resetInsecureMode", GoMethod: "ResetInsecureMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetJwtClientTimeout", GoMethod: "ResetJwtClientTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetJwtExpireTimeout", GoMethod: "ResetJwtExpireTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetKeepSessionAlive", GoMethod: "ResetKeepSessionAlive"},
			_jsii_.MemberMethod{JsiiMethod: "resetLoginTimeout", GoMethod: "ResetLoginTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogQueryParameters", GoMethod: "ResetLogQueryParameters"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogQueryText", GoMethod: "ResetLogQueryText"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxRetryCount", GoMethod: "ResetMaxRetryCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetOauthAuthorizationUrl", GoMethod: "ResetOauthAuthorizationUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetOauthClientId", GoMethod: "ResetOauthClientId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOauthClientSecret", GoMethod: "ResetOauthClientSecret"},
			_jsii_.MemberMethod{JsiiMethod: "resetOauthRedirectUri", GoMethod: "ResetOauthRedirectUri"},
			_jsii_.MemberMethod{JsiiMethod: "resetOauthScope", GoMethod: "ResetOauthScope"},
			_jsii_.MemberMethod{JsiiMethod: "resetOauthTokenRequestUrl", GoMethod: "ResetOauthTokenRequestUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetOcspFailOpen", GoMethod: "ResetOcspFailOpen"},
			_jsii_.MemberMethod{JsiiMethod: "resetOktaUrl", GoMethod: "ResetOktaUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetOrganizationName", GoMethod: "ResetOrganizationName"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetParams", GoMethod: "ResetParams"},
			_jsii_.MemberMethod{JsiiMethod: "resetPasscode", GoMethod: "ResetPasscode"},
			_jsii_.MemberMethod{JsiiMethod: "resetPasscodeInPassword", GoMethod: "ResetPasscodeInPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetPassword", GoMethod: "ResetPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetPort", GoMethod: "ResetPort"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreviewFeaturesEnabled", GoMethod: "ResetPreviewFeaturesEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetPrivateKey", GoMethod: "ResetPrivateKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetPrivateKeyPassphrase", GoMethod: "ResetPrivateKeyPassphrase"},
			_jsii_.MemberMethod{JsiiMethod: "resetProfile", GoMethod: "ResetProfile"},
			_jsii_.MemberMethod{JsiiMethod: "resetProtocol", GoMethod: "ResetProtocol"},
			_jsii_.MemberMethod{JsiiMethod: "resetRequestTimeout", GoMethod: "ResetRequestTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetRole", GoMethod: "ResetRole"},
			_jsii_.MemberMethod{JsiiMethod: "resetSkipTomlFilePermissionVerification", GoMethod: "ResetSkipTomlFilePermissionVerification"},
			_jsii_.MemberMethod{JsiiMethod: "resetTmpDirectoryPath", GoMethod: "ResetTmpDirectoryPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetToken", GoMethod: "ResetToken"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenAccessor", GoMethod: "ResetTokenAccessor"},
			_jsii_.MemberMethod{JsiiMethod: "resetUseLegacyTomlFile", GoMethod: "ResetUseLegacyTomlFile"},
			_jsii_.MemberMethod{JsiiMethod: "resetUser", GoMethod: "ResetUser"},
			_jsii_.MemberMethod{JsiiMethod: "resetValidateDefaultParameters", GoMethod: "ResetValidateDefaultParameters"},
			_jsii_.MemberMethod{JsiiMethod: "resetWarehouse", GoMethod: "ResetWarehouse"},
			_jsii_.MemberMethod{JsiiMethod: "resetWorkloadIdentityEntraResource", GoMethod: "ResetWorkloadIdentityEntraResource"},
			_jsii_.MemberMethod{JsiiMethod: "resetWorkloadIdentityProvider", GoMethod: "ResetWorkloadIdentityProvider"},
			_jsii_.MemberProperty{JsiiProperty: "role", GoGetter: "Role"},
			_jsii_.MemberProperty{JsiiProperty: "roleInput", GoGetter: "RoleInput"},
			_jsii_.MemberProperty{JsiiProperty: "skipTomlFilePermissionVerification", GoGetter: "SkipTomlFilePermissionVerification"},
			_jsii_.MemberProperty{JsiiProperty: "skipTomlFilePermissionVerificationInput", GoGetter: "SkipTomlFilePermissionVerificationInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformProviderSource", GoGetter: "TerraformProviderSource"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "tmpDirectoryPath", GoGetter: "TmpDirectoryPath"},
			_jsii_.MemberProperty{JsiiProperty: "tmpDirectoryPathInput", GoGetter: "TmpDirectoryPathInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "token", GoGetter: "Token"},
			_jsii_.MemberProperty{JsiiProperty: "tokenAccessor", GoGetter: "TokenAccessor"},
			_jsii_.MemberProperty{JsiiProperty: "tokenAccessorInput", GoGetter: "TokenAccessorInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenInput", GoGetter: "TokenInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "useLegacyTomlFile", GoGetter: "UseLegacyTomlFile"},
			_jsii_.MemberProperty{JsiiProperty: "useLegacyTomlFileInput", GoGetter: "UseLegacyTomlFileInput"},
			_jsii_.MemberProperty{JsiiProperty: "user", GoGetter: "User"},
			_jsii_.MemberProperty{JsiiProperty: "userInput", GoGetter: "UserInput"},
			_jsii_.MemberProperty{JsiiProperty: "validateDefaultParameters", GoGetter: "ValidateDefaultParameters"},
			_jsii_.MemberProperty{JsiiProperty: "validateDefaultParametersInput", GoGetter: "ValidateDefaultParametersInput"},
			_jsii_.MemberProperty{JsiiProperty: "warehouse", GoGetter: "Warehouse"},
			_jsii_.MemberProperty{JsiiProperty: "warehouseInput", GoGetter: "WarehouseInput"},
			_jsii_.MemberProperty{JsiiProperty: "workloadIdentityEntraResource", GoGetter: "WorkloadIdentityEntraResource"},
			_jsii_.MemberProperty{JsiiProperty: "workloadIdentityEntraResourceInput", GoGetter: "WorkloadIdentityEntraResourceInput"},
			_jsii_.MemberProperty{JsiiProperty: "workloadIdentityProvider", GoGetter: "WorkloadIdentityProvider"},
			_jsii_.MemberProperty{JsiiProperty: "workloadIdentityProviderInput", GoGetter: "WorkloadIdentityProviderInput"},
		},
		func() interface{} {
			j := jsiiProxy_SnowflakeProvider{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformProvider)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-snowflake.provider.SnowflakeProviderConfig",
		reflect.TypeOf((*SnowflakeProviderConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-snowflake.provider.SnowflakeProviderTokenAccessor",
		reflect.TypeOf((*SnowflakeProviderTokenAccessor)(nil)).Elem(),
	)
}
