// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package currentorganizationaccount

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-snowflake.currentOrganizationAccount.CurrentOrganizationAccount",
		reflect.TypeOf((*CurrentOrganizationAccount)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "abortDetachedQuery", GoGetter: "AbortDetachedQuery"},
			_jsii_.MemberProperty{JsiiProperty: "abortDetachedQueryInput", GoGetter: "AbortDetachedQueryInput"},
			_jsii_.MemberProperty{JsiiProperty: "activePythonProfiler", GoGetter: "ActivePythonProfiler"},
			_jsii_.MemberProperty{JsiiProperty: "activePythonProfilerInput", GoGetter: "ActivePythonProfilerInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "allowClientMfaCaching", GoGetter: "AllowClientMfaCaching"},
			_jsii_.MemberProperty{JsiiProperty: "allowClientMfaCachingInput", GoGetter: "AllowClientMfaCachingInput"},
			_jsii_.MemberProperty{JsiiProperty: "allowIdToken", GoGetter: "AllowIdToken"},
			_jsii_.MemberProperty{JsiiProperty: "allowIdTokenInput", GoGetter: "AllowIdTokenInput"},
			_jsii_.MemberProperty{JsiiProperty: "autocommit", GoGetter: "Autocommit"},
			_jsii_.MemberProperty{JsiiProperty: "autocommitInput", GoGetter: "AutocommitInput"},
			_jsii_.MemberProperty{JsiiProperty: "baseLocationPrefix", GoGetter: "BaseLocationPrefix"},
			_jsii_.MemberProperty{JsiiProperty: "baseLocationPrefixInput", GoGetter: "BaseLocationPrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "binaryInputFormat", GoGetter: "BinaryInputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "binaryInputFormatInput", GoGetter: "BinaryInputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "binaryOutputFormat", GoGetter: "BinaryOutputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "binaryOutputFormatInput", GoGetter: "BinaryOutputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "catalog", GoGetter: "Catalog"},
			_jsii_.MemberProperty{JsiiProperty: "catalogInput", GoGetter: "CatalogInput"},
			_jsii_.MemberProperty{JsiiProperty: "catalogSync", GoGetter: "CatalogSync"},
			_jsii_.MemberProperty{JsiiProperty: "catalogSyncInput", GoGetter: "CatalogSyncInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clientEnableLogInfoStatementParameters", GoGetter: "ClientEnableLogInfoStatementParameters"},
			_jsii_.MemberProperty{JsiiProperty: "clientEnableLogInfoStatementParametersInput", GoGetter: "ClientEnableLogInfoStatementParametersInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientEncryptionKeySize", GoGetter: "ClientEncryptionKeySize"},
			_jsii_.MemberProperty{JsiiProperty: "clientEncryptionKeySizeInput", GoGetter: "ClientEncryptionKeySizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientMemoryLimit", GoGetter: "ClientMemoryLimit"},
			_jsii_.MemberProperty{JsiiProperty: "clientMemoryLimitInput", GoGetter: "ClientMemoryLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientMetadataRequestUseConnectionCtx", GoGetter: "ClientMetadataRequestUseConnectionCtx"},
			_jsii_.MemberProperty{JsiiProperty: "clientMetadataRequestUseConnectionCtxInput", GoGetter: "ClientMetadataRequestUseConnectionCtxInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientMetadataUseSessionDatabase", GoGetter: "ClientMetadataUseSessionDatabase"},
			_jsii_.MemberProperty{JsiiProperty: "clientMetadataUseSessionDatabaseInput", GoGetter: "ClientMetadataUseSessionDatabaseInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientPrefetchThreads", GoGetter: "ClientPrefetchThreads"},
			_jsii_.MemberProperty{JsiiProperty: "clientPrefetchThreadsInput", GoGetter: "ClientPrefetchThreadsInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientResultChunkSize", GoGetter: "ClientResultChunkSize"},
			_jsii_.MemberProperty{JsiiProperty: "clientResultChunkSizeInput", GoGetter: "ClientResultChunkSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientResultColumnCaseInsensitive", GoGetter: "ClientResultColumnCaseInsensitive"},
			_jsii_.MemberProperty{JsiiProperty: "clientResultColumnCaseInsensitiveInput", GoGetter: "ClientResultColumnCaseInsensitiveInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientSessionKeepAlive", GoGetter: "ClientSessionKeepAlive"},
			_jsii_.MemberProperty{JsiiProperty: "clientSessionKeepAliveHeartbeatFrequency", GoGetter: "ClientSessionKeepAliveHeartbeatFrequency"},
			_jsii_.MemberProperty{JsiiProperty: "clientSessionKeepAliveHeartbeatFrequencyInput", GoGetter: "ClientSessionKeepAliveHeartbeatFrequencyInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientSessionKeepAliveInput", GoGetter: "ClientSessionKeepAliveInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientTimestampTypeMapping", GoGetter: "ClientTimestampTypeMapping"},
			_jsii_.MemberProperty{JsiiProperty: "clientTimestampTypeMappingInput", GoGetter: "ClientTimestampTypeMappingInput"},
			_jsii_.MemberProperty{JsiiProperty: "comment", GoGetter: "Comment"},
			_jsii_.MemberProperty{JsiiProperty: "commentInput", GoGetter: "CommentInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "cortexEnabledCrossRegion", GoGetter: "CortexEnabledCrossRegion"},
			_jsii_.MemberProperty{JsiiProperty: "cortexEnabledCrossRegionInput", GoGetter: "CortexEnabledCrossRegionInput"},
			_jsii_.MemberProperty{JsiiProperty: "cortexModelsAllowlist", GoGetter: "CortexModelsAllowlist"},
			_jsii_.MemberProperty{JsiiProperty: "cortexModelsAllowlistInput", GoGetter: "CortexModelsAllowlistInput"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "csvTimestampFormat", GoGetter: "CsvTimestampFormat"},
			_jsii_.MemberProperty{JsiiProperty: "csvTimestampFormatInput", GoGetter: "CsvTimestampFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "dataRetentionTimeInDays", GoGetter: "DataRetentionTimeInDays"},
			_jsii_.MemberProperty{JsiiProperty: "dataRetentionTimeInDaysInput", GoGetter: "DataRetentionTimeInDaysInput"},
			_jsii_.MemberProperty{JsiiProperty: "dateInputFormat", GoGetter: "DateInputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "dateInputFormatInput", GoGetter: "DateInputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "dateOutputFormat", GoGetter: "DateOutputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "dateOutputFormatInput", GoGetter: "DateOutputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultDdlCollation", GoGetter: "DefaultDdlCollation"},
			_jsii_.MemberProperty{JsiiProperty: "defaultDdlCollationInput", GoGetter: "DefaultDdlCollationInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultNotebookComputePoolCpu", GoGetter: "DefaultNotebookComputePoolCpu"},
			_jsii_.MemberProperty{JsiiProperty: "defaultNotebookComputePoolCpuInput", GoGetter: "DefaultNotebookComputePoolCpuInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultNotebookComputePoolGpu", GoGetter: "DefaultNotebookComputePoolGpu"},
			_jsii_.MemberProperty{JsiiProperty: "defaultNotebookComputePoolGpuInput", GoGetter: "DefaultNotebookComputePoolGpuInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultNullOrdering", GoGetter: "DefaultNullOrdering"},
			_jsii_.MemberProperty{JsiiProperty: "defaultNullOrderingInput", GoGetter: "DefaultNullOrderingInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultStreamlitNotebookWarehouse", GoGetter: "DefaultStreamlitNotebookWarehouse"},
			_jsii_.MemberProperty{JsiiProperty: "defaultStreamlitNotebookWarehouseInput", GoGetter: "DefaultStreamlitNotebookWarehouseInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "disableUiDownloadButton", GoGetter: "DisableUiDownloadButton"},
			_jsii_.MemberProperty{JsiiProperty: "disableUiDownloadButtonInput", GoGetter: "DisableUiDownloadButtonInput"},
			_jsii_.MemberProperty{JsiiProperty: "disableUserPrivilegeGrants", GoGetter: "DisableUserPrivilegeGrants"},
			_jsii_.MemberProperty{JsiiProperty: "disableUserPrivilegeGrantsInput", GoGetter: "DisableUserPrivilegeGrantsInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableAutomaticSensitiveDataClassificationLog", GoGetter: "EnableAutomaticSensitiveDataClassificationLog"},
			_jsii_.MemberProperty{JsiiProperty: "enableAutomaticSensitiveDataClassificationLogInput", GoGetter: "EnableAutomaticSensitiveDataClassificationLogInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableEgressCostOptimizer", GoGetter: "EnableEgressCostOptimizer"},
			_jsii_.MemberProperty{JsiiProperty: "enableEgressCostOptimizerInput", GoGetter: "EnableEgressCostOptimizerInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableIdentifierFirstLogin", GoGetter: "EnableIdentifierFirstLogin"},
			_jsii_.MemberProperty{JsiiProperty: "enableIdentifierFirstLoginInput", GoGetter: "EnableIdentifierFirstLoginInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableInternalStagesPrivatelink", GoGetter: "EnableInternalStagesPrivatelink"},
			_jsii_.MemberProperty{JsiiProperty: "enableInternalStagesPrivatelinkInput", GoGetter: "EnableInternalStagesPrivatelinkInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableTriSecretAndRekeyOptOutForImageRepository", GoGetter: "EnableTriSecretAndRekeyOptOutForImageRepository"},
			_jsii_.MemberProperty{JsiiProperty: "enableTriSecretAndRekeyOptOutForImageRepositoryInput", GoGetter: "EnableTriSecretAndRekeyOptOutForImageRepositoryInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableTriSecretAndRekeyOptOutForSpcsBlockStorage", GoGetter: "EnableTriSecretAndRekeyOptOutForSpcsBlockStorage"},
			_jsii_.MemberProperty{JsiiProperty: "enableTriSecretAndRekeyOptOutForSpcsBlockStorageInput", GoGetter: "EnableTriSecretAndRekeyOptOutForSpcsBlockStorageInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableUnhandledExceptionsReporting", GoGetter: "EnableUnhandledExceptionsReporting"},
			_jsii_.MemberProperty{JsiiProperty: "enableUnhandledExceptionsReportingInput", GoGetter: "EnableUnhandledExceptionsReportingInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableUnloadPhysicalTypeOptimization", GoGetter: "EnableUnloadPhysicalTypeOptimization"},
			_jsii_.MemberProperty{JsiiProperty: "enableUnloadPhysicalTypeOptimizationInput", GoGetter: "EnableUnloadPhysicalTypeOptimizationInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableUnredactedQuerySyntaxError", GoGetter: "EnableUnredactedQuerySyntaxError"},
			_jsii_.MemberProperty{JsiiProperty: "enableUnredactedQuerySyntaxErrorInput", GoGetter: "EnableUnredactedQuerySyntaxErrorInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableUnredactedSecureObjectError", GoGetter: "EnableUnredactedSecureObjectError"},
			_jsii_.MemberProperty{JsiiProperty: "enableUnredactedSecureObjectErrorInput", GoGetter: "EnableUnredactedSecureObjectErrorInput"},
			_jsii_.MemberProperty{JsiiProperty: "enforceNetworkRulesForInternalStages", GoGetter: "EnforceNetworkRulesForInternalStages"},
			_jsii_.MemberProperty{JsiiProperty: "enforceNetworkRulesForInternalStagesInput", GoGetter: "EnforceNetworkRulesForInternalStagesInput"},
			_jsii_.MemberProperty{JsiiProperty: "errorOnNondeterministicMerge", GoGetter: "ErrorOnNondeterministicMerge"},
			_jsii_.MemberProperty{JsiiProperty: "errorOnNondeterministicMergeInput", GoGetter: "ErrorOnNondeterministicMergeInput"},
			_jsii_.MemberProperty{JsiiProperty: "errorOnNondeterministicUpdate", GoGetter: "ErrorOnNondeterministicUpdate"},
			_jsii_.MemberProperty{JsiiProperty: "errorOnNondeterministicUpdateInput", GoGetter: "ErrorOnNondeterministicUpdateInput"},
			_jsii_.MemberProperty{JsiiProperty: "eventTable", GoGetter: "EventTable"},
			_jsii_.MemberProperty{JsiiProperty: "eventTableInput", GoGetter: "EventTableInput"},
			_jsii_.MemberProperty{JsiiProperty: "externalOauthAddPrivilegedRolesToBlockedList", GoGetter: "ExternalOauthAddPrivilegedRolesToBlockedList"},
			_jsii_.MemberProperty{JsiiProperty: "externalOauthAddPrivilegedRolesToBlockedListInput", GoGetter: "ExternalOauthAddPrivilegedRolesToBlockedListInput"},
			_jsii_.MemberProperty{JsiiProperty: "externalVolume", GoGetter: "ExternalVolume"},
			_jsii_.MemberProperty{JsiiProperty: "externalVolumeInput", GoGetter: "ExternalVolumeInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberProperty{JsiiProperty: "geographyOutputFormat", GoGetter: "GeographyOutputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "geographyOutputFormatInput", GoGetter: "GeographyOutputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "geometryOutputFormat", GoGetter: "GeometryOutputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "geometryOutputFormatInput", GoGetter: "GeometryOutputFormatInput"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "hybridTableLockTimeout", GoGetter: "HybridTableLockTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "hybridTableLockTimeoutInput", GoGetter: "HybridTableLockTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "initialReplicationSizeLimitInTb", GoGetter: "InitialReplicationSizeLimitInTb"},
			_jsii_.MemberProperty{JsiiProperty: "initialReplicationSizeLimitInTbInput", GoGetter: "InitialReplicationSizeLimitInTbInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "jdbcTreatDecimalAsInt", GoGetter: "JdbcTreatDecimalAsInt"},
			_jsii_.MemberProperty{JsiiProperty: "jdbcTreatDecimalAsIntInput", GoGetter: "JdbcTreatDecimalAsIntInput"},
			_jsii_.MemberProperty{JsiiProperty: "jdbcTreatTimestampNtzAsUtc", GoGetter: "JdbcTreatTimestampNtzAsUtc"},
			_jsii_.MemberProperty{JsiiProperty: "jdbcTreatTimestampNtzAsUtcInput", GoGetter: "JdbcTreatTimestampNtzAsUtcInput"},
			_jsii_.MemberProperty{JsiiProperty: "jdbcUseSessionTimezone", GoGetter: "JdbcUseSessionTimezone"},
			_jsii_.MemberProperty{JsiiProperty: "jdbcUseSessionTimezoneInput", GoGetter: "JdbcUseSessionTimezoneInput"},
			_jsii_.MemberProperty{JsiiProperty: "jsonIndent", GoGetter: "JsonIndent"},
			_jsii_.MemberProperty{JsiiProperty: "jsonIndentInput", GoGetter: "JsonIndentInput"},
			_jsii_.MemberProperty{JsiiProperty: "jsTreatIntegerAsBigint", GoGetter: "JsTreatIntegerAsBigint"},
			_jsii_.MemberProperty{JsiiProperty: "jsTreatIntegerAsBigintInput", GoGetter: "JsTreatIntegerAsBigintInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "listingAutoFulfillmentReplicationRefreshSchedule", GoGetter: "ListingAutoFulfillmentReplicationRefreshSchedule"},
			_jsii_.MemberProperty{JsiiProperty: "listingAutoFulfillmentReplicationRefreshScheduleInput", GoGetter: "ListingAutoFulfillmentReplicationRefreshScheduleInput"},
			_jsii_.MemberProperty{JsiiProperty: "lockTimeout", GoGetter: "LockTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "lockTimeoutInput", GoGetter: "LockTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "logLevel", GoGetter: "LogLevel"},
			_jsii_.MemberProperty{JsiiProperty: "logLevelInput", GoGetter: "LogLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxConcurrencyLevel", GoGetter: "MaxConcurrencyLevel"},
			_jsii_.MemberProperty{JsiiProperty: "maxConcurrencyLevelInput", GoGetter: "MaxConcurrencyLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxDataExtensionTimeInDays", GoGetter: "MaxDataExtensionTimeInDays"},
			_jsii_.MemberProperty{JsiiProperty: "maxDataExtensionTimeInDaysInput", GoGetter: "MaxDataExtensionTimeInDaysInput"},
			_jsii_.MemberProperty{JsiiProperty: "metricLevel", GoGetter: "MetricLevel"},
			_jsii_.MemberProperty{JsiiProperty: "metricLevelInput", GoGetter: "MetricLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "minDataRetentionTimeInDays", GoGetter: "MinDataRetentionTimeInDays"},
			_jsii_.MemberProperty{JsiiProperty: "minDataRetentionTimeInDaysInput", GoGetter: "MinDataRetentionTimeInDaysInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "multiStatementCount", GoGetter: "MultiStatementCount"},
			_jsii_.MemberProperty{JsiiProperty: "multiStatementCountInput", GoGetter: "MultiStatementCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkPolicy", GoGetter: "NetworkPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "networkPolicyInput", GoGetter: "NetworkPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "noorderSequenceAsDefault", GoGetter: "NoorderSequenceAsDefault"},
			_jsii_.MemberProperty{JsiiProperty: "noorderSequenceAsDefaultInput", GoGetter: "NoorderSequenceAsDefaultInput"},
			_jsii_.MemberProperty{JsiiProperty: "oauthAddPrivilegedRolesToBlockedList", GoGetter: "OauthAddPrivilegedRolesToBlockedList"},
			_jsii_.MemberProperty{JsiiProperty: "oauthAddPrivilegedRolesToBlockedListInput", GoGetter: "OauthAddPrivilegedRolesToBlockedListInput"},
			_jsii_.MemberProperty{JsiiProperty: "odbcTreatDecimalAsInt", GoGetter: "OdbcTreatDecimalAsInt"},
			_jsii_.MemberProperty{JsiiProperty: "odbcTreatDecimalAsIntInput", GoGetter: "OdbcTreatDecimalAsIntInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "passwordPolicy", GoGetter: "PasswordPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "passwordPolicyInput", GoGetter: "PasswordPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "periodicDataRekeying", GoGetter: "PeriodicDataRekeying"},
			_jsii_.MemberProperty{JsiiProperty: "periodicDataRekeyingInput", GoGetter: "PeriodicDataRekeyingInput"},
			_jsii_.MemberProperty{JsiiProperty: "pipeExecutionPaused", GoGetter: "PipeExecutionPaused"},
			_jsii_.MemberProperty{JsiiProperty: "pipeExecutionPausedInput", GoGetter: "PipeExecutionPausedInput"},
			_jsii_.MemberProperty{JsiiProperty: "preventUnloadToInlineUrl", GoGetter: "PreventUnloadToInlineUrl"},
			_jsii_.MemberProperty{JsiiProperty: "preventUnloadToInlineUrlInput", GoGetter: "PreventUnloadToInlineUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "preventUnloadToInternalStages", GoGetter: "PreventUnloadToInternalStages"},
			_jsii_.MemberProperty{JsiiProperty: "preventUnloadToInternalStagesInput", GoGetter: "PreventUnloadToInternalStagesInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putTimeouts", GoMethod: "PutTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "pythonProfilerModules", GoGetter: "PythonProfilerModules"},
			_jsii_.MemberProperty{JsiiProperty: "pythonProfilerModulesInput", GoGetter: "PythonProfilerModulesInput"},
			_jsii_.MemberProperty{JsiiProperty: "pythonProfilerTargetStage", GoGetter: "PythonProfilerTargetStage"},
			_jsii_.MemberProperty{JsiiProperty: "pythonProfilerTargetStageInput", GoGetter: "PythonProfilerTargetStageInput"},
			_jsii_.MemberProperty{JsiiProperty: "queryTag", GoGetter: "QueryTag"},
			_jsii_.MemberProperty{JsiiProperty: "queryTagInput", GoGetter: "QueryTagInput"},
			_jsii_.MemberProperty{JsiiProperty: "quotedIdentifiersIgnoreCase", GoGetter: "QuotedIdentifiersIgnoreCase"},
			_jsii_.MemberProperty{JsiiProperty: "quotedIdentifiersIgnoreCaseInput", GoGetter: "QuotedIdentifiersIgnoreCaseInput"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "replaceInvalidCharacters", GoGetter: "ReplaceInvalidCharacters"},
			_jsii_.MemberProperty{JsiiProperty: "replaceInvalidCharactersInput", GoGetter: "ReplaceInvalidCharactersInput"},
			_jsii_.MemberProperty{JsiiProperty: "requireStorageIntegrationForStageCreation", GoGetter: "RequireStorageIntegrationForStageCreation"},
			_jsii_.MemberProperty{JsiiProperty: "requireStorageIntegrationForStageCreationInput", GoGetter: "RequireStorageIntegrationForStageCreationInput"},
			_jsii_.MemberProperty{JsiiProperty: "requireStorageIntegrationForStageOperation", GoGetter: "RequireStorageIntegrationForStageOperation"},
			_jsii_.MemberProperty{JsiiProperty: "requireStorageIntegrationForStageOperationInput", GoGetter: "RequireStorageIntegrationForStageOperationInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAbortDetachedQuery", GoMethod: "ResetAbortDetachedQuery"},
			_jsii_.MemberMethod{JsiiMethod: "resetActivePythonProfiler", GoMethod: "ResetActivePythonProfiler"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowClientMfaCaching", GoMethod: "ResetAllowClientMfaCaching"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowIdToken", GoMethod: "ResetAllowIdToken"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutocommit", GoMethod: "ResetAutocommit"},
			_jsii_.MemberMethod{JsiiMethod: "resetBaseLocationPrefix", GoMethod: "ResetBaseLocationPrefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetBinaryInputFormat", GoMethod: "ResetBinaryInputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetBinaryOutputFormat", GoMethod: "ResetBinaryOutputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetCatalog", GoMethod: "ResetCatalog"},
			_jsii_.MemberMethod{JsiiMethod: "resetCatalogSync", GoMethod: "ResetCatalogSync"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientEnableLogInfoStatementParameters", GoMethod: "ResetClientEnableLogInfoStatementParameters"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientEncryptionKeySize", GoMethod: "ResetClientEncryptionKeySize"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientMemoryLimit", GoMethod: "ResetClientMemoryLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientMetadataRequestUseConnectionCtx", GoMethod: "ResetClientMetadataRequestUseConnectionCtx"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientMetadataUseSessionDatabase", GoMethod: "ResetClientMetadataUseSessionDatabase"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientPrefetchThreads", GoMethod: "ResetClientPrefetchThreads"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientResultChunkSize", GoMethod: "ResetClientResultChunkSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientResultColumnCaseInsensitive", GoMethod: "ResetClientResultColumnCaseInsensitive"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientSessionKeepAlive", GoMethod: "ResetClientSessionKeepAlive"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientSessionKeepAliveHeartbeatFrequency", GoMethod: "ResetClientSessionKeepAliveHeartbeatFrequency"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientTimestampTypeMapping", GoMethod: "ResetClientTimestampTypeMapping"},
			_jsii_.MemberMethod{JsiiMethod: "resetComment", GoMethod: "ResetComment"},
			_jsii_.MemberMethod{JsiiMethod: "resetCortexEnabledCrossRegion", GoMethod: "ResetCortexEnabledCrossRegion"},
			_jsii_.MemberMethod{JsiiMethod: "resetCortexModelsAllowlist", GoMethod: "ResetCortexModelsAllowlist"},
			_jsii_.MemberMethod{JsiiMethod: "resetCsvTimestampFormat", GoMethod: "ResetCsvTimestampFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetDataRetentionTimeInDays", GoMethod: "ResetDataRetentionTimeInDays"},
			_jsii_.MemberMethod{JsiiMethod: "resetDateInputFormat", GoMethod: "ResetDateInputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetDateOutputFormat", GoMethod: "ResetDateOutputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultDdlCollation", GoMethod: "ResetDefaultDdlCollation"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultNotebookComputePoolCpu", GoMethod: "ResetDefaultNotebookComputePoolCpu"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultNotebookComputePoolGpu", GoMethod: "ResetDefaultNotebookComputePoolGpu"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultNullOrdering", GoMethod: "ResetDefaultNullOrdering"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultStreamlitNotebookWarehouse", GoMethod: "ResetDefaultStreamlitNotebookWarehouse"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableUiDownloadButton", GoMethod: "ResetDisableUiDownloadButton"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableUserPrivilegeGrants", GoMethod: "ResetDisableUserPrivilegeGrants"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableAutomaticSensitiveDataClassificationLog", GoMethod: "ResetEnableAutomaticSensitiveDataClassificationLog"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableEgressCostOptimizer", GoMethod: "ResetEnableEgressCostOptimizer"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableIdentifierFirstLogin", GoMethod: "ResetEnableIdentifierFirstLogin"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableInternalStagesPrivatelink", GoMethod: "ResetEnableInternalStagesPrivatelink"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableTriSecretAndRekeyOptOutForImageRepository", GoMethod: "ResetEnableTriSecretAndRekeyOptOutForImageRepository"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableTriSecretAndRekeyOptOutForSpcsBlockStorage", GoMethod: "ResetEnableTriSecretAndRekeyOptOutForSpcsBlockStorage"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableUnhandledExceptionsReporting", GoMethod: "ResetEnableUnhandledExceptionsReporting"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableUnloadPhysicalTypeOptimization", GoMethod: "ResetEnableUnloadPhysicalTypeOptimization"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableUnredactedQuerySyntaxError", GoMethod: "ResetEnableUnredactedQuerySyntaxError"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableUnredactedSecureObjectError", GoMethod: "ResetEnableUnredactedSecureObjectError"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnforceNetworkRulesForInternalStages", GoMethod: "ResetEnforceNetworkRulesForInternalStages"},
			_jsii_.MemberMethod{JsiiMethod: "resetErrorOnNondeterministicMerge", GoMethod: "ResetErrorOnNondeterministicMerge"},
			_jsii_.MemberMethod{JsiiMethod: "resetErrorOnNondeterministicUpdate", GoMethod: "ResetErrorOnNondeterministicUpdate"},
			_jsii_.MemberMethod{JsiiMethod: "resetEventTable", GoMethod: "ResetEventTable"},
			_jsii_.MemberMethod{JsiiMethod: "resetExternalOauthAddPrivilegedRolesToBlockedList", GoMethod: "ResetExternalOauthAddPrivilegedRolesToBlockedList"},
			_jsii_.MemberMethod{JsiiMethod: "resetExternalVolume", GoMethod: "ResetExternalVolume"},
			_jsii_.MemberMethod{JsiiMethod: "resetGeographyOutputFormat", GoMethod: "ResetGeographyOutputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetGeometryOutputFormat", GoMethod: "ResetGeometryOutputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetHybridTableLockTimeout", GoMethod: "ResetHybridTableLockTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetInitialReplicationSizeLimitInTb", GoMethod: "ResetInitialReplicationSizeLimitInTb"},
			_jsii_.MemberMethod{JsiiMethod: "resetJdbcTreatDecimalAsInt", GoMethod: "ResetJdbcTreatDecimalAsInt"},
			_jsii_.MemberMethod{JsiiMethod: "resetJdbcTreatTimestampNtzAsUtc", GoMethod: "ResetJdbcTreatTimestampNtzAsUtc"},
			_jsii_.MemberMethod{JsiiMethod: "resetJdbcUseSessionTimezone", GoMethod: "ResetJdbcUseSessionTimezone"},
			_jsii_.MemberMethod{JsiiMethod: "resetJsonIndent", GoMethod: "ResetJsonIndent"},
			_jsii_.MemberMethod{JsiiMethod: "resetJsTreatIntegerAsBigint", GoMethod: "ResetJsTreatIntegerAsBigint"},
			_jsii_.MemberMethod{JsiiMethod: "resetListingAutoFulfillmentReplicationRefreshSchedule", GoMethod: "ResetListingAutoFulfillmentReplicationRefreshSchedule"},
			_jsii_.MemberMethod{JsiiMethod: "resetLockTimeout", GoMethod: "ResetLockTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogLevel", GoMethod: "ResetLogLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxConcurrencyLevel", GoMethod: "ResetMaxConcurrencyLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxDataExtensionTimeInDays", GoMethod: "ResetMaxDataExtensionTimeInDays"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetricLevel", GoMethod: "ResetMetricLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinDataRetentionTimeInDays", GoMethod: "ResetMinDataRetentionTimeInDays"},
			_jsii_.MemberMethod{JsiiMethod: "resetMultiStatementCount", GoMethod: "ResetMultiStatementCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetworkPolicy", GoMethod: "ResetNetworkPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetNoorderSequenceAsDefault", GoMethod: "ResetNoorderSequenceAsDefault"},
			_jsii_.MemberMethod{JsiiMethod: "resetOauthAddPrivilegedRolesToBlockedList", GoMethod: "ResetOauthAddPrivilegedRolesToBlockedList"},
			_jsii_.MemberMethod{JsiiMethod: "resetOdbcTreatDecimalAsInt", GoMethod: "ResetOdbcTreatDecimalAsInt"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPasswordPolicy", GoMethod: "ResetPasswordPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetPeriodicDataRekeying", GoMethod: "ResetPeriodicDataRekeying"},
			_jsii_.MemberMethod{JsiiMethod: "resetPipeExecutionPaused", GoMethod: "ResetPipeExecutionPaused"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreventUnloadToInlineUrl", GoMethod: "ResetPreventUnloadToInlineUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreventUnloadToInternalStages", GoMethod: "ResetPreventUnloadToInternalStages"},
			_jsii_.MemberMethod{JsiiMethod: "resetPythonProfilerModules", GoMethod: "ResetPythonProfilerModules"},
			_jsii_.MemberMethod{JsiiMethod: "resetPythonProfilerTargetStage", GoMethod: "ResetPythonProfilerTargetStage"},
			_jsii_.MemberMethod{JsiiMethod: "resetQueryTag", GoMethod: "ResetQueryTag"},
			_jsii_.MemberMethod{JsiiMethod: "resetQuotedIdentifiersIgnoreCase", GoMethod: "ResetQuotedIdentifiersIgnoreCase"},
			_jsii_.MemberMethod{JsiiMethod: "resetReplaceInvalidCharacters", GoMethod: "ResetReplaceInvalidCharacters"},
			_jsii_.MemberMethod{JsiiMethod: "resetRequireStorageIntegrationForStageCreation", GoMethod: "ResetRequireStorageIntegrationForStageCreation"},
			_jsii_.MemberMethod{JsiiMethod: "resetRequireStorageIntegrationForStageOperation", GoMethod: "ResetRequireStorageIntegrationForStageOperation"},
			_jsii_.MemberMethod{JsiiMethod: "resetResourceMonitor", GoMethod: "ResetResourceMonitor"},
			_jsii_.MemberMethod{JsiiMethod: "resetRowsPerResultset", GoMethod: "ResetRowsPerResultset"},
			_jsii_.MemberMethod{JsiiMethod: "resetS3StageVpceDnsName", GoMethod: "ResetS3StageVpceDnsName"},
			_jsii_.MemberMethod{JsiiMethod: "resetSearchPath", GoMethod: "ResetSearchPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerlessTaskMaxStatementSize", GoMethod: "ResetServerlessTaskMaxStatementSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerlessTaskMinStatementSize", GoMethod: "ResetServerlessTaskMinStatementSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetSessionPolicy", GoMethod: "ResetSessionPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetSimulatedDataSharingConsumer", GoMethod: "ResetSimulatedDataSharingConsumer"},
			_jsii_.MemberMethod{JsiiMethod: "resetSsoLoginPage", GoMethod: "ResetSsoLoginPage"},
			_jsii_.MemberMethod{JsiiMethod: "resetStatementQueuedTimeoutInSeconds", GoMethod: "ResetStatementQueuedTimeoutInSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetStatementTimeoutInSeconds", GoMethod: "ResetStatementTimeoutInSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetStorageSerializationPolicy", GoMethod: "ResetStorageSerializationPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetStrictJsonOutput", GoMethod: "ResetStrictJsonOutput"},
			_jsii_.MemberMethod{JsiiMethod: "resetSuspendTaskAfterNumFailures", GoMethod: "ResetSuspendTaskAfterNumFailures"},
			_jsii_.MemberMethod{JsiiMethod: "resetTaskAutoRetryAttempts", GoMethod: "ResetTaskAutoRetryAttempts"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeInputFormat", GoMethod: "ResetTimeInputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeOutputFormat", GoMethod: "ResetTimeOutputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeouts", GoMethod: "ResetTimeouts"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimestampDayIsAlways24H", GoMethod: "ResetTimestampDayIsAlways24H"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimestampInputFormat", GoMethod: "ResetTimestampInputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimestampLtzOutputFormat", GoMethod: "ResetTimestampLtzOutputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimestampNtzOutputFormat", GoMethod: "ResetTimestampNtzOutputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimestampOutputFormat", GoMethod: "ResetTimestampOutputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimestampTypeMapping", GoMethod: "ResetTimestampTypeMapping"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimestampTzOutputFormat", GoMethod: "ResetTimestampTzOutputFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimezone", GoMethod: "ResetTimezone"},
			_jsii_.MemberMethod{JsiiMethod: "resetTraceLevel", GoMethod: "ResetTraceLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetTransactionAbortOnError", GoMethod: "ResetTransactionAbortOnError"},
			_jsii_.MemberMethod{JsiiMethod: "resetTransactionDefaultIsolationLevel", GoMethod: "ResetTransactionDefaultIsolationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetTwoDigitCenturyStart", GoMethod: "ResetTwoDigitCenturyStart"},
			_jsii_.MemberMethod{JsiiMethod: "resetUnsupportedDdlAction", GoMethod: "ResetUnsupportedDdlAction"},
			_jsii_.MemberMethod{JsiiMethod: "resetUseCachedResult", GoMethod: "ResetUseCachedResult"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserTaskManagedInitialWarehouseSize", GoMethod: "ResetUserTaskManagedInitialWarehouseSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserTaskMinimumTriggerIntervalInSeconds", GoMethod: "ResetUserTaskMinimumTriggerIntervalInSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserTaskTimeoutMs", GoMethod: "ResetUserTaskTimeoutMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetWeekOfYearPolicy", GoMethod: "ResetWeekOfYearPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetWeekStart", GoMethod: "ResetWeekStart"},
			_jsii_.MemberProperty{JsiiProperty: "resourceMonitor", GoGetter: "ResourceMonitor"},
			_jsii_.MemberProperty{JsiiProperty: "resourceMonitorInput", GoGetter: "ResourceMonitorInput"},
			_jsii_.MemberProperty{JsiiProperty: "rowsPerResultset", GoGetter: "RowsPerResultset"},
			_jsii_.MemberProperty{JsiiProperty: "rowsPerResultsetInput", GoGetter: "RowsPerResultsetInput"},
			_jsii_.MemberProperty{JsiiProperty: "s3StageVpceDnsName", GoGetter: "S3StageVpceDnsName"},
			_jsii_.MemberProperty{JsiiProperty: "s3StageVpceDnsNameInput", GoGetter: "S3StageVpceDnsNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "searchPath", GoGetter: "SearchPath"},
			_jsii_.MemberProperty{JsiiProperty: "searchPathInput", GoGetter: "SearchPathInput"},
			_jsii_.MemberProperty{JsiiProperty: "serverlessTaskMaxStatementSize", GoGetter: "ServerlessTaskMaxStatementSize"},
			_jsii_.MemberProperty{JsiiProperty: "serverlessTaskMaxStatementSizeInput", GoGetter: "ServerlessTaskMaxStatementSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "serverlessTaskMinStatementSize", GoGetter: "ServerlessTaskMinStatementSize"},
			_jsii_.MemberProperty{JsiiProperty: "serverlessTaskMinStatementSizeInput", GoGetter: "ServerlessTaskMinStatementSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "sessionPolicy", GoGetter: "SessionPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "sessionPolicyInput", GoGetter: "SessionPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "showOutput", GoGetter: "ShowOutput"},
			_jsii_.MemberProperty{JsiiProperty: "simulatedDataSharingConsumer", GoGetter: "SimulatedDataSharingConsumer"},
			_jsii_.MemberProperty{JsiiProperty: "simulatedDataSharingConsumerInput", GoGetter: "SimulatedDataSharingConsumerInput"},
			_jsii_.MemberProperty{JsiiProperty: "ssoLoginPage", GoGetter: "SsoLoginPage"},
			_jsii_.MemberProperty{JsiiProperty: "ssoLoginPageInput", GoGetter: "SsoLoginPageInput"},
			_jsii_.MemberProperty{JsiiProperty: "statementQueuedTimeoutInSeconds", GoGetter: "StatementQueuedTimeoutInSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "statementQueuedTimeoutInSecondsInput", GoGetter: "StatementQueuedTimeoutInSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "statementTimeoutInSeconds", GoGetter: "StatementTimeoutInSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "statementTimeoutInSecondsInput", GoGetter: "StatementTimeoutInSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "storageSerializationPolicy", GoGetter: "StorageSerializationPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "storageSerializationPolicyInput", GoGetter: "StorageSerializationPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "strictJsonOutput", GoGetter: "StrictJsonOutput"},
			_jsii_.MemberProperty{JsiiProperty: "strictJsonOutputInput", GoGetter: "StrictJsonOutputInput"},
			_jsii_.MemberProperty{JsiiProperty: "suspendTaskAfterNumFailures", GoGetter: "SuspendTaskAfterNumFailures"},
			_jsii_.MemberProperty{JsiiProperty: "suspendTaskAfterNumFailuresInput", GoGetter: "SuspendTaskAfterNumFailuresInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "taskAutoRetryAttempts", GoGetter: "TaskAutoRetryAttempts"},
			_jsii_.MemberProperty{JsiiProperty: "taskAutoRetryAttemptsInput", GoGetter: "TaskAutoRetryAttemptsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timeInputFormat", GoGetter: "TimeInputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timeInputFormatInput", GoGetter: "TimeInputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "timeOutputFormat", GoGetter: "TimeOutputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timeOutputFormatInput", GoGetter: "TimeOutputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "timeouts", GoGetter: "Timeouts"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutsInput", GoGetter: "TimeoutsInput"},
			_jsii_.MemberProperty{JsiiProperty: "timestampDayIsAlways24H", GoGetter: "TimestampDayIsAlways24H"},
			_jsii_.MemberProperty{JsiiProperty: "timestampDayIsAlways24HInput", GoGetter: "TimestampDayIsAlways24HInput"},
			_jsii_.MemberProperty{JsiiProperty: "timestampInputFormat", GoGetter: "TimestampInputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timestampInputFormatInput", GoGetter: "TimestampInputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "timestampLtzOutputFormat", GoGetter: "TimestampLtzOutputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timestampLtzOutputFormatInput", GoGetter: "TimestampLtzOutputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "timestampNtzOutputFormat", GoGetter: "TimestampNtzOutputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timestampNtzOutputFormatInput", GoGetter: "TimestampNtzOutputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "timestampOutputFormat", GoGetter: "TimestampOutputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timestampOutputFormatInput", GoGetter: "TimestampOutputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "timestampTypeMapping", GoGetter: "TimestampTypeMapping"},
			_jsii_.MemberProperty{JsiiProperty: "timestampTypeMappingInput", GoGetter: "TimestampTypeMappingInput"},
			_jsii_.MemberProperty{JsiiProperty: "timestampTzOutputFormat", GoGetter: "TimestampTzOutputFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timestampTzOutputFormatInput", GoGetter: "TimestampTzOutputFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "timezone", GoGetter: "Timezone"},
			_jsii_.MemberProperty{JsiiProperty: "timezoneInput", GoGetter: "TimezoneInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "traceLevel", GoGetter: "TraceLevel"},
			_jsii_.MemberProperty{JsiiProperty: "traceLevelInput", GoGetter: "TraceLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "transactionAbortOnError", GoGetter: "TransactionAbortOnError"},
			_jsii_.MemberProperty{JsiiProperty: "transactionAbortOnErrorInput", GoGetter: "TransactionAbortOnErrorInput"},
			_jsii_.MemberProperty{JsiiProperty: "transactionDefaultIsolationLevel", GoGetter: "TransactionDefaultIsolationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "transactionDefaultIsolationLevelInput", GoGetter: "TransactionDefaultIsolationLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "twoDigitCenturyStart", GoGetter: "TwoDigitCenturyStart"},
			_jsii_.MemberProperty{JsiiProperty: "twoDigitCenturyStartInput", GoGetter: "TwoDigitCenturyStartInput"},
			_jsii_.MemberProperty{JsiiProperty: "unsupportedDdlAction", GoGetter: "UnsupportedDdlAction"},
			_jsii_.MemberProperty{JsiiProperty: "unsupportedDdlActionInput", GoGetter: "UnsupportedDdlActionInput"},
			_jsii_.MemberProperty{JsiiProperty: "useCachedResult", GoGetter: "UseCachedResult"},
			_jsii_.MemberProperty{JsiiProperty: "useCachedResultInput", GoGetter: "UseCachedResultInput"},
			_jsii_.MemberProperty{JsiiProperty: "userTaskManagedInitialWarehouseSize", GoGetter: "UserTaskManagedInitialWarehouseSize"},
			_jsii_.MemberProperty{JsiiProperty: "userTaskManagedInitialWarehouseSizeInput", GoGetter: "UserTaskManagedInitialWarehouseSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "userTaskMinimumTriggerIntervalInSeconds", GoGetter: "UserTaskMinimumTriggerIntervalInSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "userTaskMinimumTriggerIntervalInSecondsInput", GoGetter: "UserTaskMinimumTriggerIntervalInSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "userTaskTimeoutMs", GoGetter: "UserTaskTimeoutMs"},
			_jsii_.MemberProperty{JsiiProperty: "userTaskTimeoutMsInput", GoGetter: "UserTaskTimeoutMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "weekOfYearPolicy", GoGetter: "WeekOfYearPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "weekOfYearPolicyInput", GoGetter: "WeekOfYearPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "weekStart", GoGetter: "WeekStart"},
			_jsii_.MemberProperty{JsiiProperty: "weekStartInput", GoGetter: "WeekStartInput"},
		},
		func() interface{} {
			j := jsiiProxy_CurrentOrganizationAccount{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-snowflake.currentOrganizationAccount.CurrentOrganizationAccountConfig",
		reflect.TypeOf((*CurrentOrganizationAccountConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-snowflake.currentOrganizationAccount.CurrentOrganizationAccountShowOutput",
		reflect.TypeOf((*CurrentOrganizationAccountShowOutput)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-snowflake.currentOrganizationAccount.CurrentOrganizationAccountShowOutputList",
		reflect.TypeOf((*CurrentOrganizationAccountShowOutputList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_CurrentOrganizationAccountShowOutputList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-snowflake.currentOrganizationAccount.CurrentOrganizationAccountShowOutputOutputReference",
		reflect.TypeOf((*CurrentOrganizationAccountShowOutputOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accountLocator", GoGetter: "AccountLocator"},
			_jsii_.MemberProperty{JsiiProperty: "accountLocatorUrl", GoGetter: "AccountLocatorUrl"},
			_jsii_.MemberProperty{JsiiProperty: "accountName", GoGetter: "AccountName"},
			_jsii_.MemberProperty{JsiiProperty: "accountOldUrlLastUsed", GoGetter: "AccountOldUrlLastUsed"},
			_jsii_.MemberProperty{JsiiProperty: "accountOldUrlSavedOn", GoGetter: "AccountOldUrlSavedOn"},
			_jsii_.MemberProperty{JsiiProperty: "accountUrl", GoGetter: "AccountUrl"},
			_jsii_.MemberProperty{JsiiProperty: "comment", GoGetter: "Comment"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "consumptionBillingEntityName", GoGetter: "ConsumptionBillingEntityName"},
			_jsii_.MemberProperty{JsiiProperty: "createdOn", GoGetter: "CreatedOn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "edition", GoGetter: "Edition"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "isEventsAccount", GoGetter: "IsEventsAccount"},
			_jsii_.MemberProperty{JsiiProperty: "isOrgAdmin", GoGetter: "IsOrgAdmin"},
			_jsii_.MemberProperty{JsiiProperty: "isOrganizationAccount", GoGetter: "IsOrganizationAccount"},
			_jsii_.MemberProperty{JsiiProperty: "managedAccounts", GoGetter: "ManagedAccounts"},
			_jsii_.MemberProperty{JsiiProperty: "marketplaceConsumerBillingEntityName", GoGetter: "MarketplaceConsumerBillingEntityName"},
			_jsii_.MemberProperty{JsiiProperty: "marketplaceProviderBillingEntityName", GoGetter: "MarketplaceProviderBillingEntityName"},
			_jsii_.MemberProperty{JsiiProperty: "oldAccountUrl", GoGetter: "OldAccountUrl"},
			_jsii_.MemberProperty{JsiiProperty: "organizationName", GoGetter: "OrganizationName"},
			_jsii_.MemberProperty{JsiiProperty: "organizationOldUrl", GoGetter: "OrganizationOldUrl"},
			_jsii_.MemberProperty{JsiiProperty: "organizationOldUrlLastUsed", GoGetter: "OrganizationOldUrlLastUsed"},
			_jsii_.MemberProperty{JsiiProperty: "organizationOldUrlSavedOn", GoGetter: "OrganizationOldUrlSavedOn"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "snowflakeRegion", GoGetter: "SnowflakeRegion"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_CurrentOrganizationAccountShowOutputOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-snowflake.currentOrganizationAccount.CurrentOrganizationAccountTimeouts",
		reflect.TypeOf((*CurrentOrganizationAccountTimeouts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-snowflake.currentOrganizationAccount.CurrentOrganizationAccountTimeoutsOutputReference",
		reflect.TypeOf((*CurrentOrganizationAccountTimeoutsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "create", GoGetter: "Create"},
			_jsii_.MemberProperty{JsiiProperty: "createInput", GoGetter: "CreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "delete", GoGetter: "Delete"},
			_jsii_.MemberProperty{JsiiProperty: "deleteInput", GoGetter: "DeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "read", GoGetter: "Read"},
			_jsii_.MemberProperty{JsiiProperty: "readInput", GoGetter: "ReadInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreate", GoMethod: "ResetCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelete", GoMethod: "ResetDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resetRead", GoMethod: "ResetRead"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpdate", GoMethod: "ResetUpdate"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "update", GoGetter: "Update"},
			_jsii_.MemberProperty{JsiiProperty: "updateInput", GoGetter: "UpdateInput"},
		},
		func() interface{} {
			j := jsiiProxy_CurrentOrganizationAccountTimeoutsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexObject)
			return &j
		},
	)
}
